export const FETCH_CHARACTER = "FETCH_CHARACTER";
export const FETCH_CHARACTER_SUCCESS = "FETCH_CHARACTER_SUCCESS";
export const FETCH_CHARACTER_ERROR = "FETCH_CHARACTER_ERROR";

export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_ERROR = "FETCH_CHARACTERS_ERROR";

export const EDIT_CHARACTER = "EDIT_CHARACTER";
export const EDIT_CHARACTER_SUCCESS = "EDIT_CHARACTER_SUCCESS";
export const EDIT_CHARACTER_ERROR = "EDIT_CHARACTER_ERROR";

export const FETCH_SERIES = "FETCH_SERIES";
export const FETCH_SERIES_SUCCESS = "FETCH_SERIES_SUCCESS";
export const FETCH_SERIES_ERROR = "FETCH_SERIES_ERROR";

export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "FETCH_EVENTS_ERROR";

export const FETCH_STORIES = "FETCH_STORIES";
export const FETCH_STORIES_SUCCESS = "FETCH_STORIES_SUCCESS";
export const FETCH_STORIES_ERROR = "FETCH_STORIES_ERROR";

export const FETCH_COMICS = "FETCH_COMICS";
export const FETCH_COMICS_SUCCESS = "FETCH_COMICS_SUCCESS";
export const FETCH_COMICS_ERROR = "FETCH_COMICS_ERROR";

export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS";
export const SEARCH_CHARACTERS_SUCCESS = "SEARCH_CHARACTERS_SUCCESS";
export const SEARCH_CHARACTERS_ERROR = "SEARCH_CHARACTERS_ERROR";
