export const FETCH_CHARACTER = "FETCH_CHARACTER";
export const FETCH_CHARACTER_SUCCESS = "FETCH_CHARACTER_SUCCESS";
export const FETCH_CHARACTER_ERROR = "FETCH_CHARACTER_ERROR";

export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_ERROR = "FETCH_CHARACTERS_ERROR";

export const EDIT_CHARACTER = "EDIT_CHARACTER";
export const EDIT_CHARACTER_SUCCESS = "EDIT_CHARACTER_SUCCESS";
export const EDIT_CHARACTER_ERROR = "EDIT_CHARACTER_ERROR";

export const FETCH_SERIES = "FETCH_SERIES";
export const FETCH_SERIES_SUCCESS = "FETCH_SERIES_SUCCESS";
export const FETCH_SERIES_ERROR = "FETCH_SERIES_ERROR";

export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS";
export const SEARCH_CHARACTERS_SUCCESS = "SEARCH_CHARACTERS_SUCCESS";
export const SEARCH_CHARACTERS_ERROR = "SEARCH_CHARACTERS_ERROR";